# Generated by Django 5.0.7 on 2025-11-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Agente')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('role', models.CharField(default='atendente', help_text='Ex: atendente, recepcionista, consultor', max_length=50, verbose_name='Função')),
                ('sector', models.CharField(default='manicure/pedicure', help_text='Ex: manicure/pedicure, beleza, estética', max_length=100, verbose_name='Setor')),
                ('language', models.CharField(default='pt-BR', help_text='Código do idioma (pt-BR, en-US, etc)', max_length=10, verbose_name='Idioma')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('greeting', models.TextField(default='Olá {{cliente_nome}}! Eu sou {{agente_nome}}, atendente da Unhas Fast 💅. Como posso te ajudar hoje?', help_text='Use {{cliente_nome}} e {{agente_nome}} para personalização', verbose_name='Saudação Inicial')),
                ('tone', models.CharField(default='objetivo, simpático e claro', help_text='Descreva o tom desejado (ex: profissional, amigável, casual)', max_length=200, verbose_name='Tom de Voz')),
                ('style_guidelines', models.TextField(default='Use linguagem simples e amigável. Seja objetivo mas cordial. \nSempre confirme detalhes importantes como data, horário e serviço. \nSe não souber algo, seja honesto e ofereça alternativas.', help_text='Instruções sobre como o agente deve se comunicar', verbose_name='Diretrizes de Estilo')),
                ('business_hours', models.JSONField(blank=True, default=dict, help_text='JSON com horários por dia da semana', verbose_name='Horário de Funcionamento')),
                ('knowledge_base', models.TextField(default='## Serviços Oferecidos\n\n- **Manicure básica** (30min) - R$ 25,00\n- **Pedicure básica** (45min) - R$ 35,00\n- **Manicure + Pedicure** (1h15min) - R$ 55,00\n- **Spa de mãos** (45min) - R$ 40,00\n- **Spa de pés** (1h) - R$ 50,00\n- **Alongamento de unhas** (1h30min) - R$ 80,00\n- **Nail art personalizada** (30min adicional) - R$ 20,00\n\n## Políticas do Salão\n\n### Agendamento\n- Agendamentos podem ser feitos por telefone, WhatsApp ou pessoalmente\n- Recomendamos agendar com pelo menos 24h de antecedência\n- Horários disponíveis: Segunda a Sexta 09:00-18:00, Sábado 09:00-14:00\n\n### Atrasos e Remarcações\n- Tolerância de atraso: 10 minutos\n- Remarcação gratuita: até 24h de antecedência\n- Cancelamento com menos de 24h: taxa de 50% do valor do serviço\n- Falta sem aviso: taxa de 100%\n\n### Formas de Pagamento\n- Dinheiro\n- Cartão de débito e crédito\n- PIX\n- Não trabalhamos com cheque\n\n## Cuidados Pós-Atendimento\n\n### Após Esmaltação\n- Evite água quente por 2h após a aplicação\n- Não mergulhe as mãos em água nas primeiras 4h\n- Use luvas ao fazer limpeza pesada ou lavar louça\n- Evite piscina e mar nas primeiras 24h\n\n### Cuidados Diários\n- Hidrate cutículas diariamente com óleo específico\n- Use base fortalecedora se as unhas forem frágeis\n- Lixe sempre na mesma direção\n- Não use as unhas como ferramenta\n\n### Alongamento de Unhas\n- Retoque recomendado a cada 15-20 dias\n- Nunca arranque ou force a remoção\n- Mantenha as unhas hidratadas\n- Evite impactos fortes\n\n## Perguntas Frequentes\n\n**Precisa agendar para todos os serviços?**\nSim, trabalhamos apenas com agendamento para garantir melhor atendimento.\n\n**Pode levar esmalte próprio?**\nSim, mas verificamos a qualidade antes da aplicação.\n\n**Fazem atendimento a domicílio?**\nNão, apenas no salão.\n\n**Atendem homens?**\nSim, oferecemos serviços de manicure e pedicure masculina.\n\n**Tem estacionamento?**\nTemos convênio com estacionamento ao lado (2h grátis).\n', help_text='Informações sobre serviços, políticas, etc (Markdown)', verbose_name='Base de Conhecimento')),
                ('fallback_message', models.TextField(default='Desculpe, não entendi bem sua solicitação. Pode reformular? \nOu se preferir, posso transferir para um atendente humano.', help_text='Quando o agente não entende a solicitação', verbose_name='Mensagem de Fallback')),
                ('escalation_rule', models.TextField(default='Transferir para atendente humano quando:\n- Cliente solicitar explicitamente\n- Reclamação ou problema não resolvido\n- Situação complexa que exija decisão humana\n- Cliente demonstrar insatisfação após 2 tentativas', help_text='Quando e como transferir para atendente humano', verbose_name='Regra de Escalonamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Agente',
                'verbose_name_plural': 'Agentes',
                'ordering': ['-created_at'],
                'unique_together': {('padaria', 'slug')},
            },
        ),
    ]
