# Generated by Django 5.0.7 on 2025-11-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='role',
            field=models.CharField(choices=[('atendente', 'Atendente'), ('recepcionista', 'Recepcionista'), ('consultor', 'Consultor(a)'), ('vendedor', 'Vendedor(a)'), ('suporte', 'Suporte Técnico'), ('assistente', 'Assistente Virtual'), ('gerente', 'Gerente'), ('especialista', 'Especialista')], default='atendente', help_text='Selecione a função do agente', max_length=50, verbose_name='Função'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tone',
            field=models.CharField(choices=[('profissional_formal', 'Profissional e Formal'), ('amigavel_casual', 'Amigável e Casual'), ('objetivo_direto', 'Objetivo e Direto'), ('simpatico_acolhedor', 'Simpático e Acolhedor'), ('energetico_entusiasmado', 'Energético e Entusiasmado'), ('calmo_paciente', 'Calmo e Paciente'), ('tecnico_detalhista', 'Técnico e Detalhista'), ('consultivo_educativo', 'Consultivo e Educativo')], default='simpatico_acolhedor', help_text='Selecione o tom de voz do agente', max_length=50, verbose_name='Tom de Voz'),
        ),
    ]
