# Generated by Django 5.1.13 on 2025-11-13 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_alter_agent_role_alter_agent_tone'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='knowledge_pdf',
            field=models.FileField(blank=True, help_text='Upload do PDF com informações do negócio (será extraído automaticamente)', null=True, upload_to='knowledge_pdfs/', verbose_name='PDF de Conhecimento'),
        ),
    ]
