# Generated by Django 5.1.13 on 2025-11-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_agent_knowledge_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='n8n_webhook_url',
            field=models.URLField(blank=True, help_text='URL do webhook do N8N para notificar atualizações (ex: quando PDF é upado)', max_length=500, null=True, verbose_name='Webhook N8N'),
        ),
    ]
