# Generated by Django 5.1.11 on 2025-11-15 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_agent_n8n_webhook_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='knowledge_pdf_category',
            field=models.CharField(blank=True, default='', help_text='Ex: Produtos, FAQ, Políticas, Procedimentos', max_length=50, verbose_name='Categoria do PDF'),
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_pdf_text',
            field=models.TextField(blank=True, default='', help_text='Texto extraído automaticamente do PDF para busca e preview', verbose_name='Texto Extraído do PDF'),
        ),
        migrations.AddField(
            model_name='agent',
            name='knowledge_updated_at',
            field=models.DateTimeField(blank=True, help_text='Data da última atualização do conhecimento (PDF ou texto)', null=True, verbose_name='Conhecimento Atualizado em'),
        ),
        migrations.AddField(
            model_name='agent',
            name='max_response_time',
            field=models.IntegerField(default=30, help_text='Tempo máximo esperado para o agente responder', verbose_name='Tempo Máximo de Resposta (segundos)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='out_of_hours_message',
            field=models.TextField(default='Olá! No momento estamos fora do horário de atendimento. Nosso horário de funcionamento é de Segunda a Sexta das 9h às 18h e Sábado das 9h às 14h. Deixe sua mensagem que retornaremos assim que possível!', help_text='Mensagem enviada quando fora do horário de atendimento', verbose_name='Mensagem Fora do Horário'),
        ),
        migrations.AddField(
            model_name='agent',
            name='personality',
            field=models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('amigavel', 'Amigável'), ('profissional', 'Profissional'), ('profissional_formal', 'Profissional e Formal'), ('amigavel_casual', 'Amigável e Casual'), ('objetivo_direto', 'Objetivo e Direto'), ('simpatico_acolhedor', 'Simpático e Acolhedor'), ('energetico_entusiasmado', 'Energético e Entusiasmado'), ('calmo_paciente', 'Calmo e Paciente'), ('tecnico_detalhista', 'Técnico e Detalhista'), ('consultivo_educativo', 'Consultivo e Educativo')], default='amigavel', help_text='Define o tom de voz e personalidade do agente', max_length=50, verbose_name='Personalidade/Tom'),
        ),
        migrations.AddField(
            model_name='agent',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('manutencao', 'Em Manutenção')], default='ativo', help_text='Status atual do agente', max_length=20, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='agent',
            name='transfer_keywords',
            field=models.TextField(blank=True, default='falar com humano, atendente, pessoa, reclamação, problema sério', help_text='Palavras separadas por vírgula que acionam transferência para humano', verbose_name='Palavras-chave de Transferência'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='greeting',
            field=models.TextField(default='Olá! Eu sou {{agente_nome}}, como posso te ajudar hoje?', help_text='Primeira mensagem enviada ao usuário. Use {{agente_nome}} para personalização', verbose_name='Mensagem de Boas-vindas'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo (deprecated - usar status)'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='knowledge_pdf',
            field=models.FileField(blank=True, help_text='Upload do PDF com informações do negócio', null=True, upload_to='knowledge_pdfs/', verbose_name='PDF de Conhecimento'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='tone',
            field=models.CharField(choices=[('formal', 'Formal'), ('casual', 'Casual'), ('amigavel', 'Amigável'), ('profissional', 'Profissional'), ('profissional_formal', 'Profissional e Formal'), ('amigavel_casual', 'Amigável e Casual'), ('objetivo_direto', 'Objetivo e Direto'), ('simpatico_acolhedor', 'Simpático e Acolhedor'), ('energetico_entusiasmado', 'Energético e Entusiasmado'), ('calmo_paciente', 'Calmo e Paciente'), ('tecnico_detalhista', 'Técnico e Detalhista'), ('consultivo_educativo', 'Consultivo e Educativo')], default='amigavel', help_text='Selecione o tom de voz do agente', max_length=50, verbose_name='Tom de Voz (deprecated - usar personality)'),
        ),
    ]
