# Generated by Django 5.1.11 on 2025-12-11 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_knowledge_pdf_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agent',
            name='greeting',
            field=models.TextField(default='Olá! Eu sou {{agente_nome}}, assistente virtual da {{padaria_nome}}. Como posso te ajudar hoje?', help_text='Primeira mensagem enviada ao usuário. Use {{agente_nome}} e {{padaria_nome}} para personalização', verbose_name='Mensagem de Boas-vindas'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='knowledge_base',
            field=models.TextField(default='## Produtos da Padaria\n\n### Pães\n- **Pão Francês** - R$ 0,50 (unidade)\n- **Pão de Forma** - R$ 8,00 (pacote)\n- **Pão Integral** - R$ 12,00 (pacote)\n- **Pão de Queijo** - R$ 3,00 (unidade)\n- **Croissant** - R$ 5,00 (unidade)\n\n### Doces\n- **Bolo de Chocolate** - R$ 35,00 (inteiro) / R$ 6,00 (fatia)\n- **Bolo de Cenoura** - R$ 30,00 (inteiro) / R$ 5,00 (fatia)\n- **Sonho** - R$ 4,00 (unidade)\n- **Brigadeiro** - R$ 2,50 (unidade)\n\n### Salgados\n- **Coxinha** - R$ 5,00\n- **Esfiha** - R$ 4,00\n- **Empada** - R$ 5,00\n- **Pastel** - R$ 6,00\n\n### Bebidas\n- **Café Expresso** - R$ 4,00\n- **Cappuccino** - R$ 7,00\n- **Suco Natural** - R$ 8,00\n- **Refrigerante** - R$ 5,00\n\n## Políticas\n\n### Encomendas\n- Encomendas devem ser feitas com 24h de antecedência\n- Para bolos decorados, mínimo 48h de antecedência\n- Pagamento de 50% no ato da encomenda\n\n### Entregas\n- Entrega disponível para pedidos acima de R$ 50,00\n- Taxa de entrega: R$ 5,00 (até 5km)\n- Horário de entrega: 8h às 18h\n\n### Formas de Pagamento\n- Dinheiro\n- Cartão de débito e crédito\n- PIX\n', help_text='Informações sobre produtos, serviços, políticas, etc (Markdown)', verbose_name='Base de Conhecimento'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='out_of_hours_message',
            field=models.TextField(default='Olá! No momento estamos fora do horário de atendimento. Nosso horário de funcionamento é de Segunda a Sexta das 6h às 20h e Sábado das 6h às 14h. Deixe sua mensagem que retornaremos assim que possível!', help_text='Mensagem enviada quando fora do horário de atendimento', verbose_name='Mensagem Fora do Horário'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='sector',
            field=models.CharField(default='padaria', help_text='Ex: padaria, confeitaria, café', max_length=100, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='agent',
            name='style_guidelines',
            field=models.TextField(default='Use linguagem simples e amigável. Seja objetivo mas cordial. \nSempre confirme detalhes importantes como pedido e horário de retirada. \nSe não souber algo, seja honesto e ofereça alternativas.', help_text='Instruções sobre como o agente deve se comunicar', verbose_name='Diretrizes de Estilo'),
        ),
    ]
