# Generated by Django 5.1.11 on 2025-12-11 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0006_add_agent_to_apikey'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Se definido, essa API Key só terá acesso a este agente específico', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='agents.agent', verbose_name='Agente'),
        ),
    ]
