# Generated by Django 5.1.11 on 2025-12-11 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_audit_padaria_8a3705_idx',
            old_name='audit_audit_organiz_c1c99d_idx',
        ),
    ]
