# Generated by Django 5.0.7 on 2025-11-01 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='N8nConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webhook_url', models.URLField(blank=True, help_text='URL para onde enviaremos eventos', max_length=500, verbose_name='URL do Webhook n8n')),
                ('api_token', models.CharField(blank=True, help_text='Token para autenticar chamadas ao n8n', max_length=200, verbose_name='Token de API n8n')),
                ('enabled', models.BooleanField(default=False, help_text='Ativar/desativar integração', verbose_name='Habilitado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('padaria', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='n8n_config', to='organizations.padaria', verbose_name='Padaria')),
            ],
            options={
                'verbose_name': 'Configuração n8n',
                'verbose_name_plural': 'Configurações n8n',
            },
        ),
    ]
